local logo = paintutils.loadImage("disk/assets/logo.nfp")
local image1 = paintutils.loadImage("disk/assets/loading1.nfp")
local image2 = paintutils.loadImage("disk/assets/loading2.nfp")
local image3 = paintutils.loadImage("disk/assets/loading3.nfp")
local image4 = paintutils.loadImage("disk/assets/loading4.nfp")
local image5 = paintutils.loadImage("disk/assets/loading5.nfp")
term.clear()
paintutils.drawImage(logo, 1, 1)
paintutils.drawImage(image1, 4, 1)
sleep(0.5)
paintutils.drawImage(image2, 4, 1)
sleep(0.5)
paintutils.drawImage(image3, 4, 1)
sleep(0.5)
paintutils.drawImage(image2, 4, 1)
sleep(0.5)
paintutils.drawImage(image1, 4, 1)
sleep(0.5)
paintutils.drawImage(image2, 4, 1)
sleep(0.5)
paintutils.drawImage(image3, 4, 1)
sleep(0.5)
paintutils.drawImage(image2, 4, 1)
sleep(0.5)
paintutils.drawImage(image1, 4, 1)
sleep(0.5)
paintutils.drawImage(image4, 4, 1)
sleep(0.2)
paintutils.drawImage(image5, 4, 1)
sleep(0.2)
paintutils.drawImage(image4, 4, 1)
sleep(0.2)
paintutils.drawImage(image5, 4, 1)
sleep(0.2)
paintutils.drawImage(image4, 4, 1)
sleep(0.2)
paintutils.drawImage(image5, 4, 1)
sleep(0.2)
paintutils.drawImage(image4, 4, 1)
sleep(0.2)
term.clear()
term.setCursorPos(1,1)
term.setBackgroundColor(colors.black)
shell.run("disk/startup/usernameset.lua")
shell.run("disk/setuser.lua")
